name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    name: Build and Test

    steps:
    - uses: actions/checkout@v3
    - name: Install gphoto2 dependency
      run: sudo apt install -y libgphoto2-dev autopoint
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
